export const OFFERS = [
  {
    title: "Start",
    oldPrice: 299,
    newPrice: 199,
    headDescription: "Free support for the first month.",
    items: [
      "Website development",
      "Responsive design",
      "Interaction design",
      "Performance optimization",
      "Cross-browser compatibility",
    ],
    recommmended: true,
    url: "offers/start",
  },
  {
    title: "Upgrade",
    oldPrice: 999,
    newPrice: 799,
    headDescription: "Perfect for growing websites.",
    items: [
      "Software upgrade",
      "Design upgrade",
      "Content upgrade",
      "Backup and disaster recovery",
      "Security",
      "Performance monitoring",
      "User experience testing",
    ],
    recommmended: false,
    url: "offers/silver",
  },
  {
    title: "CMS",
    oldPrice: 399,
    newPrice: 299,
    headDescription: "Free support for the first month",
    items: [
      "Content management system (CMS) integration",
      "E-commerce website development",
    ],
    recommmended: false,
    url: "offers/gold",
  },
  {
    title: "Platinum",
    oldPrice: 399,
    newPrice: 299,
    headDescription: "Free support for the first month",
    items: ["Single Website", "Design + RWD", "Hosting", "Maintenence"],
    recommmended: false,
    url: "offers/platinum",
  },
];
